sudo: required
services:
  - docker

before_install:
  - docker build -t wanwanzainaer/docker-react -f Dockerfile.dev .

script:
  - docker run wanwanzainaer/docker-react npm test -- --coverage
deploy:
  provider: gae
  keyfile: "My First Project-de43119b4317.json.enc"
  project: "docker"
  on:
    branch: master
