sudo: required
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_84182b89dffc_key -iv $encrypted_84182b89dffc_iv
  -in My\ First\ Project-de43119b4317.json.enc -out My\ First\ Project-de43119b4317.json
  -d
- docker build -t wanwanzainaer/docker-react -f Dockerfile.dev .
script:
- docker run wanwanzainaer/docker-react npm test -- --coverage
